Repository FRONTENDSCHOOL10/109place, pull requests merged in 2024-07, with the labels that each got.

#7 Rename : 폴더 구조 변경, kind-tiger 라이브러리
  index.html
  main.js
  package-lock.json
  package.json
  src/assets/sample.js
  src/components/alert/alert.html
  src/components/button/button.html
  src/components/header/header.html
  src/components/input/input.html
  src/components/inputCount/inputCount.html
  src/components/logo/logo.html
  src/components/navigation/navigation.html
  src/components/reviewCard/reviewCard.html
  src/components/reviewTag/reviewTag.html
  src/components/reviewTagBtn/reviewTagBtn.html
  src/components/search/search.html
  src/components/share/share.html
  src/index.html
  src/layout/sample.js
  src/lib/sample.js
  src/main.js
  src/styles/sample.scss
  vite.config.js
Labels: 🎛️ Chore, 🪜Rename:

#17 Chore : 스타일링 변수 파일 생성
  src/styles/_variables.scss
Labels: 🎛️ Chore

#20 Style : reset.css 파일 추가
  src/styles/_reset.scss
Labels: 🔧 Style

#23 Style : sr-only 파일 추가
  src/styles/_sr-only.scss
Labels: 🔧 Style

#25 Chore : eslint, prettier 패키지 설치
  package-lock.json
  package.json
Labels: 🎛️ Chore

#27 Style : 컬러 변수 추가
  src/styles/_variables.scss
Labels: 🔧 Style

#29 Style : reset.css 코드 추가
  src/styles/_reset.scss
Labels: 🔧 Style

#31 Chore : main, index 파일 옮김, Vite.config.js 루트 변경
  index.html
  main.js
  src/main.js
  vite.config.js
Labels: 🎛️ Chore

#32 html&css : 로고 컴포넌트
  src/components/logo/logo.html
  src/components/logo/logo.scss
Labels: 🎨 html&css

#34 html&css : 버튼 컴포넌트
  src/components/button/button.html
  src/components/button/button.scss
Labels: 🎨 html&css

#36 html&css : 헤더 컴포넌트
  src/components/header/header.html
  src/components/header/header.scss
Labels: 🎨 html&css

#41 html&css : 인풋 카운트 컴포넌트
  src/components/input-count/input-count.html
  src/components/input-count/input-count.js
  src/components/input-count/input-count.scss
Labels: 🎨 html&css

#40 html&css : 인풋 컴포넌트
  src/components/input/input.html
  src/components/input/input.scss
Labels: 🎨 html&css

#56 Modify: 코드 리팩토링
  index.html
  main.js
  main.scss
  src/components/navigation/navigation.html
  src/components/reviewTag/reviewTag.scss
  src/components/share/share.scss
  src/layout/footer/footer.js
  src/layout/footer/footer.scss
  src/layout/sample.js
  src/styles/common/_variables.scss
Labels: 🔨 Modify, 🛠️ Refactor

#63 [html&css] 컴포넌트 리팩토링 (헤더,리뷰태그,공유)
  src/assets/images/Broccoli.svg
  src/assets/images/Cooked Rice.svg
  src/assets/images/Face Savoring Food.svg
  src/assets/images/Thumbs Up Light Skin Tone.svg
  src/assets/images/Wine Glass.svg
  src/components/header/header.scss
  src/components/reviewTag/reviewTag.html
  src/components/reviewTag/reviewTag.scss
  src/components/share/share.html
  src/components/share/share.scss
Labels: 🎨 html&css

#64 [html&css] 마이페이지 마크업
  src/pages/my-page/main/main.html
  src/pages/my-page/main/main.js
  src/pages/my-page/main/main.scss
  src/pages/my-page/profile/profile.html
  src/pages/my-page/profile/profile.js
  src/pages/my-page/profile/profile.scss
  src/pages/my-page/review/review.html
  src/pages/my-page/review/review.js
  src/pages/my-page/review/review.scss
  src/styles/common/_index.scss
Labels: 🎨 html&css

#65 HtmlCss : 메인페이지
  index.html
  main.js
  main.scss
  src/components/input-count/input-count.js
  src/components/inputCount/inputCount.html
  src/pages/homepage/homepage.html
  src/pages/homepage/homepage.js
  src/pages/homepage/homepage.scss
  vite.config.js
Labels: 🎨 html&css

#66 [html&css] 컴포넌트 수정
  src/components/reviewCard/reviewCard.html
  src/components/reviewCard/reviewCard.scss
Labels: 🎨 html&css

#67 Refactor : 인풋 컴포넌트 수정
  src/components/input/input.html
  src/components/input/input.scss
Labels: 🛠️ Refactor, 🎨 html&css

#68 html,css : 컴포넌트 리팩토링, 마크업 변경(버튼, 검색, 네비게이션)
  src/components/button/button.html
  src/components/button/button.scss
  src/components/search/search.html
  src/components/search/search.scss
  src/layout/footer/footer.js
  src/layout/footer/footer.scss
Labels: 🛠️ Refactor, 🎨 html&css

#69 [html&css] 리뷰 태그 선택 페이지
  src/pages/review-create/tag-select.html
  src/pages/review-create/tag-select.js
  src/pages/review-create/tag-select.scss
Labels: 🎨 html&css

#70 [html&css] 리뷰 장소, 날짜 선택 페이지
  src/pages/review-create/date-place.html
  src/pages/review-create/date-place.js
  src/pages/review-create/date-place.scss
Labels: 🎨 html&css

#71 [html&css] 이미지, 리뷰 내용 입력 페이지
  src/pages/review-create/img-content.html
  src/pages/review-create/img-content.js
  src/pages/review-create/img-content.scss
Labels: 🎨 html&css

#72 html&css : 스프라이트 시트 파일 추가(svg)
  index.html
  src/assets/sample.js
  src/assets/stack.svg
Labels: 🔨 Modify, 🎨 html&css

#74 Design: 전체 화면 정렬, 전체 폰트 적용
  src/styles/common/_index.scss
  src/styles/common/_media-query.scss
  src/styles/common/_reset.scss
Labels: 🖌️ Design

#76 Refactor : 인풋 컴포넌트 접근성 추가
  src/components/input/input.html
  src/components/input/input.scss
Labels: 🛠️ Refactor

#84 modify: alert, review-card, review-tag-btn 코드와 파일이름 수정
  src/components/alert/alert.html
  src/components/alert/alert.scss
  src/components/review-card/review-card.html
  src/components/review-card/review-card.scss
  src/components/review-tag-btn/review-tag-btn.html
  src/components/review-tag-btn/review-tag-btn.scss
Labels: 🛠️ Refactor

#78 Refactor : 시안 맞춰 작업, 접근성 추가
  src/components/input-count/input-count.html
  src/components/input-count/input-count.js
  src/components/input-count/input-count.scss
Labels: 🛠️ Refactor, 🎨 html&css

#85 html, css: 컴포넌트 리팩토링, 페이지 추가
  src/assets/stack.svg
  src/components/button/button.scss
  src/components/search/search.html
  src/components/search/search.scss
  src/layout/footer/footer.js
  src/layout/footer/footer.scss
  src/pages/place-detail/place-detail.html
  src/pages/place-detail/place-detail.js
  src/pages/place-detail/place-detail.scss
  src/pages/saved-places/saved-places.html
  src/pages/saved-places/saved-places.js
  src/pages/saved-places/saved-places.scss
Labels: 🎨 html&css

#86 [html&css] 컴포넌트 리팩토링 (헤더,리뷰태그,공유)
  src/assets/images/Broccoli.svg
  src/assets/images/Cooked Rice.svg
  src/assets/images/Face Savoring Food.svg
  src/assets/images/Thumbs Up Light Skin Tone.svg
  src/assets/images/Wine Glass.svg
  src/components/header/header.html
  src/components/header/header.scss
  src/components/review-tag/review-tag.html
  src/components/review-tag/review-tag.scss
  src/components/reviewTag/reviewTag.html
  src/components/share/share.html
  src/components/share/share.scss
  src/pages/my-page/main/main.scss
Labels: 🎨 html&css

#87 html,css: 컴포넌트 코드 수정
  main.js
  src/components/button/button.html
  src/components/button/button.scss
  src/components/search/search.scss
  src/layout/footer/footer.js
  src/layout/footer/footer.scss
Labels: 🔧 Style, 🎨 html&css

#88 Refactor : 시작하기에 접근성 추가, 클래스 수정, svg이미지 use로 불러옴
  index.html
Labels: 🛠️ Refactor, 🎨 html&css

#90 HtmlCss : svg 이슈 해결(네비게이션)
  src/assets/stack.svg
  src/layout/footer/footer.js
  src/layout/footer/footer.scss
  src/pages/saved-places/saved-places.html
  src/pages/saved-places/saved-places.js
Labels: 🌟 Feat, 🖌️ Design, 🎨 html&css

#91 [html&css] review tag btn 최종수정
  src/components/review-tag-btn/review-tag-btn.html
  src/components/review-tag-btn/review-tag-btn.scss
Labels: 🔨 Modify

#92 Modify: body 전체 사이즈 변경
  src/styles/common/_media-query.scss
Labels: 🔨 Modify

#93 HtmlCss: 로그인 페이지 마크업, 스타일링
  src/components/input/input.scss
  src/pages/login/login.html
  src/pages/login/login.js
  src/pages/login/login.scss
Labels: 🎨 html&css

#96 HtmlCss : 회원가입 페이지 마크업, 스타일링
  src/components/input/input.scss
  src/pages/signup/signup.html
  src/pages/signup/signup.scss
Labels: 🎨 html&css

#97 HtmlCss : 장소 상세 페이지 마크업, 스타일링
  package-lock.json
  package.json
  src/pages/place-detail/image-sample/image 26.png
  src/pages/place-detail/image-sample/image 27.png
  src/pages/place-detail/image-sample/메인.png
  src/pages/place-detail/image-sample/아보카도.png
  src/pages/place-detail/image-sample/음료.png
  src/pages/place-detail/place-detail.html
  src/pages/place-detail/place-detail.js
  src/pages/place-detail/place-detail.scss
Labels: 🌟 Feat, 🎨 html&css

#98 Modify: 리뷰 작성- 날짜 선택 페이지 수정
  src/pages/review-create/date-place.html
  src/pages/review-create/date-place.js
  src/pages/review-create/date-place.scss
Labels: 🔨 Modify

#99 Modify: 리뷰 작성- 태그 선택 페이지 수정
  src/pages/review-create/tag-select.html
  src/pages/review-create/tag-select.js
  src/pages/review-create/tag-select.scss
Labels: 🔨 Modify

#100 Modify: 리뷰 작성- 이미지 추가 페이지 수정
  src/pages/review-create/img-content.html
  src/pages/review-create/img-content.scss
Labels: 🔨 Modify

#101 HtmlCss : 리뷰 시작 페이지 마크업
  src/pages/review-search/review-search.html
  src/pages/review-search/review-search.js
  src/pages/review-search/review-search.scss
Labels: 🎨 html&css

#102 [html&css] 홈페이지 마크업, 스타일링
  src/pages/homepage/homepage.html
  src/pages/homepage/homepage.js
  src/pages/homepage/homepage.scss
Labels: 🎨 html&css

#103 Feat : 회원가입 기능 구현중
  src/pages/signup/signup.js
Labels: 🌟 Feat

#105 Modify : PR 양식 변경, 회원가입 Js 수정
  .github/PULL_REQUEST_TEMPLATE.md
  src/pages/signup/signup.js
Labels: 🔨 Modify

#104 HTML&CSS 마이페이지 메인 마크업
  package.json
  pocketbase/pb_data/data.db
  pocketbase/pb_data/logs.db
  src/assets/logo.png
  src/pages/my-page/main/main.html
  src/pages/my-page/main/main.js
  src/pages/my-page/main/main.scss
Labels: 🎨 html&css

#106 Modify: 믹스인 파일 추가
  src/styles/common/_index.scss
  src/styles/common/_mixins.scss
Labels: 🌟 Feat, 🔨 Modify

#107 Api: 지도 api 삽입
  src/pages/review-create/date-place.html
  src/pages/review-create/date-place.js
  src/pages/review-create/date-place.scss
Labels: 🗺️ Api

#108 Feat : 회원가입 기능 수정
  src/pages/signup/signup.js
Labels: 🌟 Feat, 🔨 Modify

#109 Feat : 로그인 기능 구현
  src/pages/login/login.html
  src/pages/login/login.js
Labels: 🌟 Feat

#110 Modify : 코드 변경, 주석 추가
  src/pages/login/login.js
Labels: 🔨 Modify

#111 Feat: 체크박스 두 개까지 제한 기능
  src/pages/review-create/tag-select.html
  src/pages/review-create/tag-select.js
Labels: 🌟 Feat

#112 Feat: 선택한 날짜 로컬 스토리지에 저장
  src/pages/review-create/date-place.html
  src/pages/review-create/date-place.js
Labels: 🌟 Feat

#113 HtmlCss : 리뷰 시작 페이지 마크업, 스타일링
  src/pages/review-search/review-search.html
  src/pages/review-search/review-search.scss
Labels: 🎨 html&css

#114 [html&css] 마이페이지 메인
  src/pages/my-page/main/main.html
  src/pages/my-page/main/main.js
  src/pages/my-page/main/main.scss
Labels: 🎨 html&css

#115 HtmlCss/Feat : 리뷰 상세 페이지 마크업, 스타일링, 기능 구현
  src/pages/search-detail/search-detail.html
  src/pages/search-detail/search-detail.js
  src/pages/search-detail/search-detail.scss
Labels: 🌟 Feat, 🎨 html&css

#116 [html&css] 리뷰디테일 마크업 및 기능 추가
  src/pages/my-page/main/main.html
  src/pages/my-page/main/main.js
  src/pages/my-page/main/main.scss
  src/pages/my-page/review/review.html
  src/pages/my-page/review/review.js
  src/pages/my-page/review/review.scss
Labels: 🌟 Feat, 🎨 html&css

#118 HtmlCss/Modify : 리뷰 시작 페이지 마크업 수정, 홈페이지 SVG 깨지는 문제 수정
  public/src/assets/stack.svg
  src/pages/homepage/homepage.js
  src/pages/review-search/review-search.html
  src/pages/review-search/review-search.scss
Labels: 🔨 Modify, 🎨 html&css

#119 [HTML&CSS] 마이페이지 메인
  src/pages/my-page/main/main.js
Labels: 🎨 html&css

#120 [HTML&CSS] 리뷰디테일 마크업
  src/pages/my-page/main/main.html
  src/pages/my-page/main/main.js
  src/pages/my-page/review/review.html
  src/pages/my-page/review/review.js
  src/pages/my-page/review/review.scss
Labels: 🎨 html&css

#121 HtmlCss : 장소 저장 페이지 기본 마크업
  src/pages/saved-places/saved-places.html
  src/pages/saved-places/saved-places.js
  src/pages/saved-places/saved-places.scss
Labels: 🎨 html&css

#122 [HTML&CSS] 마이페이지 - 프로필 마크업
  src/pages/my-page/profile/profile.html
  src/pages/my-page/profile/profile.js
  src/pages/my-page/profile/profile.scss
Labels: 🎨 html&css

#123 [HTML&CSS] 마이페이지 메인
  src/pages/my-page/main/main.js
Labels: 🎨 html&css

#124 [HTML&CSS] 마이페이지 - 리뷰 디테일
  src/pages/my-page/review/review.html
  src/pages/my-page/review/review.js
  src/pages/my-page/review/review.scss
Labels: 🌟 Feat, 🎨 html&css

#126 Feat: 태그별 로컬 스토리지 추가
  src/components/review-tag-btn/review-tag-btn.scss
  src/pages/review-create/tag-select.html
  src/pages/review-create/tag-select.js
Labels: 🌟 Feat

#127 Feat : 장소 상세 페이지(중복 체크 후 가게 정보 DB에 저장하는 로직)
  src/pages/place-detail/place-detail.js
Labels: 🌟 Feat

#128 Feat : 리뷰 마커 위에 마우스 오버하면 장소 이름 띄워주는 기능 구현, 유틸 함수
  src/lib/utils/Map/searchPlace.js
  src/lib/utils/Map/searchPlaceNoName.js
  src/pages/homepage/homepage.js
Labels: 🌟 Feat

#129 Feat : 마이페이지 - 기능과css살짝 수정
  src/pages/my-page/main/main.js
  src/pages/my-page/main/main.scss
Labels: 🌟 Feat, 🎨 html&css

#130 Feat : 홈검색,리뷰검색에서 찾은 장소 DB에 올라가게 설정
  src/pages/homepage/homepage.js
  src/pages/search-detail/search-detail.js
Labels: 🌟 Feat

#131 [HTML&CSS] 버튼 마크업
  src/components/share/share.html
  src/pages/my-page/main/main.html
  src/pages/my-page/main/main.js
  src/pages/my-page/review/review-update.html
  src/pages/my-page/review/review.html
  src/pages/my-page/review/review.js
  src/pages/my-page/review/review.scss
Labels: 🎨 html&css

#133 Modify: tag-select.html 헤더 링크 변경
  src/pages/review-create/tag-select.html
  src/pages/review-create/tag-select.js
  src/pages/review-create/tag-select.scss
Labels: 🔨 Modify

#134 Modify: date-place.html 헤더 링크 변경
  src/pages/review-create/date-place.html
  src/pages/review-create/date-place.js
  src/pages/review-create/date-place.scss
Labels: 🔨 Modify

#136 HtmlCss : 리뷰 완료 페이지 마크업, 기능 구현
  src/pages/review-done/review-done.html
  src/pages/review-done/review-done.js
  src/pages/review-done/review-done.scss
Labels: 🌟 Feat, 🎨 html&css

#137 Modify: 장소 상세 페이지 렌더링
  src/pages/place-detail/place-detail.html
  src/pages/place-detail/place-detail.js
  src/pages/place-detail/place-detail.scss
Labels: 🌟 Feat, 🔨 Modify

#138 HtmlCss : 로고 이미지 교체
  index.html
  main.scss
  public/src/assets/text_logo.svg
Labels: 🎨 html&css

#139 Modify : 최상위 await 수정
  src/pages/review-done/review-done.js
Labels: 🔨 Modify

#140 Feat : 아이디, 비밀번호 중복 검사, 오류 메시지 추가
  src/pages/login/login.js
  src/pages/signup/signup.html
  src/pages/signup/signup.js
  src/pages/signup/signup.scss
Labels: 🌟 Feat

#142 Modify:중간머지
  src/pages/review-create/img-content.js
Labels: ⏱️ Test

#144 Modify: img-content 수정
  src/pages/review-create/img-content.html
  src/pages/review-create/img-content.js
  src/pages/review-create/tag-select.html
Labels: 🔨 Modify

#145 Feat : 리뷰 작성 완료시 장소 아이디 삭제
  src/pages/review-done/review-done.html
  src/pages/review-done/review-done.js
Labels: 🌟 Feat

#146 BugFix : 포켓베이스에 데이터 올라가지 않는 이슈 고침
  src/pages/review-create/img-content.html
  src/pages/review-create/img-content.js
Labels: 🍿 BugFix

#147 Modify : 접근성 대공사
  src/pages/home-search/home-search.js
  src/pages/homepage/homepage.html
  src/pages/homepage/homepage.js
  src/pages/homepage/homepage.scss
  src/pages/login/login.html
  src/pages/login/login.js
  src/pages/login/login.scss
  src/pages/review-done/review-done.html
  src/pages/review-done/review-done.js
  src/pages/review-search/review-search.html
  src/pages/search-detail/search-detail.html
  src/pages/search-detail/search-detail.js
  src/pages/signup/signup.js
Labels: 🔨 Modify

#148 Modify : 장소 상세 페이지 기능 수정
  src/pages/place-detail/place-detail.html
  src/pages/place-detail/place-detail.js
  src/pages/place-detail/place-detail.scss
Labels: 🔨 Modify

#149 Modify : 장소 저장 페이지 기능 추가
  src/pages/saved-places/saved-places.html
  src/pages/saved-places/saved-places.js
Labels: 🔨 Modify

#151 BugFix,Feat : 회원가입 안 되던 문제 해결 / 홈페이지에 시작페이지로 이동 겸 로그아웃 버튼 추가
  README.md
  index.html
  src/pages/homepage/homepage.html
  src/pages/homepage/homepage.js
  src/pages/homepage/homepage.scss
Labels: 🍿 BugFix, 🌟 Feat

#154 feat : 리뷰삭제기능
  src/pages/my-page/review/review-update.html
  src/pages/my-page/review/review-update.js
  src/pages/my-page/review/review-update.scss
  src/pages/my-page/review/review.html
  src/pages/my-page/review/review.js
Labels: 🌟 Feat

#155 Feat: 이미지 프리뷰
  src/pages/review-create/img-content.html
  src/pages/review-create/img-content.js
  src/pages/review-create/img-content.scss
  src/pages/review-create/tag-select.html
Labels: 🌟 Feat

#156 Modify: 데이터 화면에 띄우기
  src/pages/review-create/tag-select.html
  src/pages/review-create/tag-select.js
Labels: 🌟 Feat, 🔨 Modify

#152 Modify: : 장소 저장 페이지
  public/src/assets/dog2.png
  src/pages/saved-places/saved-places.html
  src/pages/saved-places/saved-places.js
  src/pages/saved-places/saved-places.scss
Labels: 🌟 Feat, 🔨 Modify

#153 Modify: : 장소 상세 페이지
  src/pages/place-detail/place-detail.html
  src/pages/place-detail/place-detail.js
  src/pages/place-detail/place-detail.scss
Labels: 🔨 Modify

#157 Modify: 데이터 관련한 코드 수정
  src/pages/review-create/date-place.html
  src/pages/review-create/date-place.js
Labels: 🔨 Modify

#158 feat : 리뷰 작성시 이동 페이지 수정
  src/pages/my-page/main/main.js
Labels: 🌟 Feat

#159 Modify: 데이터 수정
  src/pages/review-create/img-content.html
  src/pages/review-create/img-content.js
  src/pages/review-create/tag-select.html
Labels: 🔨 Modify

#160 Modify: img-content 코드변경
  src/pages/review-create/img-content.js
  src/pages/review-create/img-content.scss
Labels: 🔨 Modify

#161 Feat : 마이페이지 마크업 수정, 리뷰디테일페이지 기능추가, 프로필 삭제 및 수정 기능 추각
  src/pages/my-page/main/main.js
  src/pages/my-page/profile/profile.html
  src/pages/my-page/profile/profile.js
  src/pages/my-page/review/review-update.js
Labels: 🎨 html&css

#162 Refactor: 버튼 디자인과 로컬스토리지 변경
  src/pages/review-create/date-place.js
  src/pages/review-create/img-content.js
  src/pages/review-create/img-content.scss
  src/pages/review-create/tag-select.js
Labels: 🛠️ Refactor

#163 feat : 프로필 글자수세기 기능, 프로필 삭제시 알림창
  src/pages/my-page/profile/profile.js
Labels: 🌟 Feat

#164 feat : 리뷰삭제버튼
  src/pages/my-page/review/review-update.scss
  src/pages/my-page/review/review.js
Labels: 🌟 Feat

#166 Docs : 리드미 파일 수정
  README.md
Labels: 📄 Docs

#167 Bugfix: 리뷰 데이터 포켓베이스에 저장 성공!
  src/pages/review-create/date-place.js
  src/pages/review-create/img-content.js
Labels: 🍿 BugFix

#168 Modify: 리뷰 작성 후 이동 링크 등 약간의 수정
  src/pages/my-page/main/main.js
  src/pages/review-create/img-content.js
Labels: 🔨 Modify, 🛠️ Refactor
